name: Post

on:
    push:
      branches:
        - main
    schedule:
        - cron: "44 * * * *"

jobs:
    post:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: actions/setup-python@v6
              with:
                python-version: '3.12' 
            - uses: VaultVulp/action-pipenv@v2.0.1
              with:
                command: install
            - name: Run
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                command: python post.py
              env:
                BSKY_USER: ${{ secrets.BSKY_USER }}
                BSKY_PASS: ${{ secrets.BSKY_PASS }}
